import { describe, expect, it } from "vitest";
import { formatFromFilename, parseAnyLockfile, UnsupportedLockfileError } from "./index";
import { parsePnpmLock } from "./pnpm";
import { parseYarnLock } from "./yarn";

/**
 * These parsers decide which packages Tavik believes are installed, which
 * decides who it says can reach you. A silent misparse doesn't crash — it just
 * quietly narrows the graph, and every rule then reports a smaller, wrong
 * answer with total confidence. So the awkward real-world shapes are pinned
 * here rather than trusted to one successful scan.
 */

describe("format detection", () => {
  it("recognises each lockfile by name", () => {
    expect(formatFromFilename("package-lock.json")).toBe("npm");
    expect(formatFromFilename("npm-shrinkwrap.json")).toBe("npm");
    expect(formatFromFilename("yarn.lock")).toBe("yarn");
    expect(formatFromFilename("pnpm-lock.yaml")).toBe("pnpm");
    expect(formatFromFilename("/repo/nested/yarn.lock")).toBe("yarn");
  });

  it("returns null for anything else", () => {
    expect(formatFromFilename("package.json")).toBeNull();
    expect(formatFromFilename("readme.md")).toBeNull();
  });

  it("detects the format from contents when the name is unhelpful", () => {
    // Files arrive pasted into a textarea or renamed; the name is often absent
    // or wrong, and refusing on that basis would be a bad first impression.
    expect(parseAnyLockfile('{"lockfileVersion":3,"packages":{}}').format).toBe("npm");
    expect(parseAnyLockfile("# yarn lockfile v1\n").format).toBe("yarn");
    expect(
      parseAnyLockfile("lockfileVersion: '9.0'\npackages:\n  /a@1.0.0:\n    resolution: {}\n")
        .format,
    ).toBe("pnpm");
  });

  it("refuses something that isn't a lockfile", () => {
    expect(() => parseAnyLockfile("hello world")).toThrow(UnsupportedLockfileError);
  });
});

describe("yarn v1 (classic)", () => {
  const lock = `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


lodash@^4.17.0, lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-abc

"@babel/core@^7.20.0":
  version "7.23.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.23.0.tgz"
  dependencies:
    lodash "^4.17.21"
    "@babel/helper" "^7.0.0"

"@babel/helper@^7.0.0":
  version "7.22.5"
  resolved "https://registry.yarnpkg.com/@babel/helper/-/helper-7.22.5.tgz"
`;

  const graph = parseYarnLock(lock);
  const names = graph.packages.filter((p) => p.path !== "").map((p) => p.name);

  it("reads every resolved package", () => {
    expect(names.sort()).toEqual(["@babel/core", "@babel/helper", "lodash"]);
  });

  it("keeps scoped names intact", () => {
    // Splitting on the first `@` would turn "@babel/core" into "" — the single
    // easiest way to silently lose every scoped package in a tree.
    const scoped = graph.packages.find((p) => p.name === "@babel/core");
    expect(scoped?.version).toBe("7.23.0");
  });

  it("reads versions rather than ranges", () => {
    expect(graph.packages.find((p) => p.name === "lodash")?.version).toBe("4.17.21");
  });

  it("reads the dependency block", () => {
    const babel = graph.packages.find((p) => p.name === "@babel/core");
    expect(Object.keys(babel?.dependencies ?? {}).sort()).toEqual([
      "@babel/helper",
      "lodash",
    ]);
  });

  it("links dependencies that resolved", () => {
    expect(graph.edges).toContainEqual({
      from: "node_modules/@babel/core",
      to: "node_modules/lodash",
    });
  });

  it("treats every package as reachable from the project", () => {
    // A flat store doesn't record which packages were direct dependencies. Over-
    // reporting reachability is the safe reading; under-reporting would hide a
    // real route.
    expect(graph.edges).toContainEqual({ from: "", to: "node_modules/lodash" });
  });

  it("ignores comments and blank lines", () => {
    expect(names).not.toContain("#");
    expect(names.every((n) => n.length > 0)).toBe(true);
  });
});

describe("yarn berry (v2+)", () => {
  const lock = `__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: abc
  languageName: node

"@babel/core@npm:^7.20.0":
  version: 7.23.0
  resolution: "@babel/core@npm:7.23.0"
  dependencies:
    lodash: ^4.17.21
  languageName: node
`;

  const graph = parseYarnLock(lock);

  it("reads the YAML format", () => {
    const names = graph.packages.filter((p) => p.path !== "").map((p) => p.name).sort();
    expect(names).toEqual(["@babel/core", "lodash"]);
  });

  it("uses the resolution field for identity", () => {
    expect(graph.packages.find((p) => p.name === "lodash")?.version).toBe("4.17.21");
  });

  it("skips the metadata block", () => {
    expect(graph.packages.some((p) => p.name === "__metadata")).toBe(false);
  });

  it("reads dependencies", () => {
    expect(graph.edges).toContainEqual({
      from: "node_modules/@babel/core",
      to: "node_modules/lodash",
    });
  });
});

describe("pnpm", () => {
  it("reads the modern name@version key", () => {
    const graph = parsePnpmLock(`lockfileVersion: '9.0'
packages:
  lodash@4.17.21:
    resolution: {integrity: sha512-abc}
  '@babel/core@7.23.0':
    resolution: {integrity: sha512-def}
`);
    const names = graph.packages.filter((p) => p.path !== "").map((p) => p.name).sort();
    expect(names).toEqual(["@babel/core", "lodash"]);
  });

  it("reads the legacy /name/version key", () => {
    // Older lockfiles are everywhere; assuming only the current shape would
    // silently produce an empty graph for them.
    const graph = parsePnpmLock(`lockfileVersion: 5.4
packages:
  /lodash/4.17.21:
    resolution: {integrity: sha512-abc}
  /@babel/core/7.23.0:
    resolution: {integrity: sha512-def}
`);
    const names = graph.packages.filter((p) => p.path !== "").map((p) => p.name).sort();
    expect(names).toEqual(["@babel/core", "lodash"]);
  });

  it("reads the intermediate /name@version key", () => {
    const graph = parsePnpmLock(`lockfileVersion: '6.0'
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-abc}
`);
    expect(graph.packages.find((p) => p.name === "lodash")?.version).toBe("4.17.21");
  });

  it("discards the peer-dependency suffix", () => {
    // "react-dom@18.2.0(react@18.2.0)" is one package, not a package with a
    // version containing brackets.
    const graph = parsePnpmLock(`lockfileVersion: '9.0'
packages:
  react-dom@18.2.0(react@18.2.0):
    resolution: {integrity: sha512-abc}
`);
    const pkg = graph.packages.find((p) => p.name === "react-dom");
    expect(pkg?.version).toBe("18.2.0");
  });

  it("prefers snapshots when present, as v9 splits the tree out", () => {
    const graph = parsePnpmLock(`lockfileVersion: '9.0'
packages:
  lodash@4.17.21:
    resolution: {integrity: sha512-abc}
snapshots:
  lodash@4.17.21: {}
  chalk@5.3.0:
    dependencies:
      lodash: 4.17.21
`);
    const names = graph.packages.filter((p) => p.path !== "").map((p) => p.name).sort();
    expect(names).toEqual(["chalk", "lodash"]);
    expect(graph.edges).toContainEqual({
      from: "node_modules/chalk",
      to: "node_modules/lodash",
    });
  });

  it("survives malformed YAML rather than throwing", () => {
    // One unparseable file must not abort a scan that could still map most of
    // the tree.
    expect(() => parsePnpmLock("packages:\n  - [unclosed")).not.toThrow();
  });
});
