#!/usr/bin/env node
/**
 * Prepare the local HydraDB volume before first boot.
 *
 * HydraDB reads its bearer token from the file named by GRAPH_AUTH_TOKEN_FILE,
 * which lives on the mounted data volume. That file has to exist before the
 * container starts, so this script creates it and mirrors the token into
 * .env.local for the Next.js app.
 *
 * Safe to re-run: an existing token is reused rather than rotated, so restarting
 * the stack does not invalidate a running app.
 */

import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = join(projectRoot, ".hydradb-data");
const tokenPath = join(dataDir, "auth-token");
const envPath = join(projectRoot, ".env.local");

/** HydraDB's documented sample token is 32 bytes; match that width exactly. */
function generateToken() {
  return randomBytes(24).toString("base64url");
}

async function ensureToken() {
  await mkdir(join(dataDir, "store"), { recursive: true });
  await mkdir(join(dataDir, "cache"), { recursive: true });

  if (existsSync(tokenPath)) {
    const existing = (await readFile(tokenPath, "utf8")).trim();
    if (existing.length > 0) {
      console.log("• Reusing existing HydraDB auth token.");
      return existing;
    }
  }

  const token = generateToken();
  // No trailing newline: the server compares the file contents to the header.
  await writeFile(tokenPath, token, { encoding: "utf8", mode: 0o600 });
  console.log("• Generated a new HydraDB auth token.");
  return token;
}

/** Set or replace a single key in .env.local, preserving everything else. */
function upsertEnv(contents, key, value) {
  const line = `${key}=${value}`;
  const pattern = new RegExp(`^${key}=.*$`, "m");
  if (pattern.test(contents)) return contents.replace(pattern, line);
  const prefix = contents.length === 0 || contents.endsWith("\n") ? "" : "\n";
  return contents + prefix + line + "\n";
}

async function ensureEnvFile(token) {
  let contents = existsSync(envPath) ? await readFile(envPath, "utf8") : "";
  if (contents.length === 0) {
    contents =
      "# Local development configuration for Tavik.\n" +
      "# Generated by `npm run hydra:setup`. Not committed — see .gitignore.\n\n";
  }

  contents = upsertEnv(contents, "HYDRA_URL", "http://127.0.0.1:8443");
  contents = upsertEnv(contents, "HYDRA_TOKEN", token);
  contents = upsertEnv(contents, "HYDRA_GRAPH_ID", "default");
  contents = upsertEnv(contents, "HYDRA_NAMESPACE", "default");
  contents = upsertEnv(contents, "HYDRA_CELL_ID", "cell-0");

  await writeFile(envPath, contents, "utf8");
  console.log("• Wrote HydraDB settings to .env.local");
}

const token = await ensureToken();
await ensureEnvFile(token);

console.log("\nHydraDB volume is ready. Start the database with:\n\n  npm run hydra:up\n");
